# SPDX-License-Identifier: GPL-2.0

# required for overlay support
DTC_FLAGS += -@

dtb-y += rzboard-hdmi.dtbo
dtb-y += rzboard-mipi.dtbo
dtb-y += rzboard-mipi-ph720128t003.dtbo
dtb-y += rzboard-lite-audio.dtbo
dtb-y += rzboard-ov5640.dtbo
dtb-y += rzboard-imx219.dtbo
